### PR TITLE
Create README.txt

### PR DESCRIPTION
**Pull request by Jeyandh**
Hi Shiva could you please review my project.

### CODE REVIEW

**Comment by Shiva-Rz** [comment]
**I have reviewed your entire file, I found some changes. Please make some changes in these files**

1. Change the bean package name into lowercase
2. Change bean class name "The first letter should be Capitalized"

**Comment by Jeyandh** [comment]
Thanks Shiva I changed the file as you mentioned above. Could please verify it once again for any more errors.

**Comment by Shiva-Rz** [comment]
Please use the appropriate method name.
And maintain the coding standards like whitespaces, etc..

**Comment by Jeyandh** [comment]
Yeah Shiva i changed that also. Anything else?

**Comment by Shiva-Rz** [comment]
Yes everything is fine. If you add comments in the code it will be helpful for understanding easily.

**Comment by Jeyandh** [comment]
Thanks for spending your time to review my project Shiva.

**Comment by Shiva-Rz** [comment]
Thank You

**Pull request merged**
